[repository]
name = "HyprOrthoLayout"
authors = ["Shawn Murali"]

[hyprortholayout]
description = "A main/secondary stack layout where the stacks are orthogonal."
authors = ["Shawn Murali"]
output = "ortholayout.so"
build = [
	"make all"
]
